### ISSUE TITLE
Geometry property is not available in any one of the models in "Digital Twins Definition Language-based RealEstateCore ontology for smart buildings"

### ISSUE THREAD

**Issue by Maheshdev-Learning** [RealEstateCore/realestatecore.github.io#18]
Hi Team,
I was referring Spatial modelling guide https://github.com/RealEstateCore/realestatecore.github.io/blob/master/docs/guides/spatial/index.md and found that mentioned geometry property is not available in any one of space/level/building interfaces in https://github.com/Azure/opendigitaltwins-building  (I'm using DTDL V2 in this repo.Just cheked in V3 also no model have geometry )
example let's take Level model; we have LevelNumber property but doesn't have geometry property. In this scenario we need to extend the ontology or anything I'm missing here.
![image](https://github.com/RealEstateCore/realestatecore.github.io/assets/72294341/64ae7d57-3ed6-4543-a9f7-e026939ea8f1)

**Comment by hammar** [comment]
Hi,

That guide you refer is for a prerelease version of RealEstateCore 4, which has a [GitHub repo here](https://github.com/RealEstateCore/rec), and [documentation here](https://dev.realestatecore.io/ontology/). 

The main difference between that prerelease doc and what we actually shipped in REC 4 back in February, is that we broke out geometries into their own classes, the [root of which is described here](https://dev.realestatecore.io/ontology/Information/Geometry/Geometry).

I hope this helps -- if not, feel free to reopen issue.
